name: animevn
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter



  flutter_bloc: ^8.1.3
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  animate_do: ^3.3.4
  # show toast message
  fluttertoast: ^8.2.2
  # play videos
  video_player: ^2.10.0
  # font
  font_awesome_flutter: ^10.0.0
  http: ^1.2.1
  #luu va ghi file json
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  path: ^1.9.0
  sqflite: ^2.4.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

